#!/bin/bash

# Function to determine the zodiac sign based on the current date
zodiac_sign() {
	# Define the start dates for all zodiac signs
	declare -A start_dates=(
		[Aquarius]=120 [Pisces]=219 [Aries]=321 [Taurus]=420 [Gemini]=521 [Cancer]=621
		[Leo]=723 [Virgo]=823 [Libra]=923 [Scorpio]=1023 [Sagittarius]=1122 [Capricorn]=1222
	)

	# Zodiac signs emojis
	declare -A zodiac_emojis=(
		[Aquarius]="♒️" [Pisces]="♓️" [Aries]="♈️" [Taurus]="♉️" [Gemini]="♊️" [Cancer]="♋️"
		[Leo]="♌️" [Virgo]="♍️" [Libra]="♎️" [Scorpio]="♏️" [Sagittarius]="♐️" [Capricorn]="♑️"
	)

	# Today's month and day in MMDD format
	today=$(date +%-m%-d)
	today=${today#0} # Remove leading zero if any

	# Determine the zodiac sign
	for sign in "${!start_dates[@]}"; do
		if ((today >= start_dates[$sign])); then
			current_sign=$sign
		fi
	done

	# Special case for Capricorn before January 20
	if ((today < 120)); then
		current_sign="Capricorn"
	fi

	echo "${zodiac_emojis[$current_sign]}"
}

case "$1" in
day_of_week)
	echo "$(date +%-u)|7"
	;;

day_of_month)
	# Current day of the month
	day=$(date +%-d)

	# Try to detect if we're using GNU date (Linux) or BSD date (macOS).
	if date --version >/dev/null 2>&1; then
		# GNU date command; likely a Linux system
		last_day=$(date -d "$(date +'%Y-%m-01') +1 month -1 day" +%d)
	else
		# BSD date command; likely a macOS system
		last_day=$(date -v+1m -v1d -v-1d +%d)
	fi

	# echo "$day/$last_day"
	echo "$day|$last_day"
	;;

day_of_year)
	# Day of the year
	day=$(date +%-j)
	# Total days in the current year, accounting for leap years
	if (($(date +%Y) % 400 == 0)); then
		leap="true"
	elif (($(date +%Y) % 100 == 0)); then
		leap="false"
	elif (($(date +%Y) % 4 == 0)); then
		leap="true"
	else
		leap="false"
	fi
	total_days=$((leap ? 366 : 365))
	echo "$day|$total_days"
	;;

week_of_year)
	echo "$(date +%V)|52"
	;;
current_month)
	echo "$(date +%-m)|12"
	;;
year_week_based)
	# 72
	echo "$(date +%g)|63"
	;;
time)
	echo "$(date +%T)"
	;;
zodiac)
	# Call the function to get zodiac sign emoji
	zodiac_sign
	;;
*)
	echo "Invalid argument: $1"
	exit 2
	;;
esac
