# Documentation --------------
# Plugins to make documentation in Vim more convenient

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
let g:echodoc#type = 'signature'
call echodoc#enable()
'''
