# Editing --------------------
# Plugins to make navigation in Vim more convenient

# [[plugins]]
# repo = 'hecal3/vim-leader-guide' # Similar to Emacs guide-key

[[plugins]]
repo = 'tpope/vim-unimpaired' # tpope/unimpaired.vim: pairs of handy bracket mappings

[[plugins]]
repo = 'tpope/vim-vinegar' # vinegar.vim: combine with netrw to create a delicious salad dressing

[[plugins]]
repo = 'moll/vim-bbye' # Delete buffers and close files in Vim without closing your windows or messing up your layout. 
on_cmd = 'Bdelete'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = 'OpenBrowser'
on_map = {nx = '<Plug>(openbrowser-smart-search)'}
hook_add = '''
    " disable netrw's gx mapping.
    let g:netrw_nogx = 1 

    " Replace said mapping
    nmap gx <Plug>(openbrowser-smart-search)
    vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim' # Brings physics-based smooth scrolling to the Vim world!
hook_add = '''
let g:comfortable_motion_scroll_down_key = "j"
let g:comfortable_motion_scroll_up_key = "k"
'''


# [[plugins]]
# repo = 'Shougo/defx.nvim' # Shougo/defx.nvim: 📁 The dark powered file explorer implementation(vaporware)


# [[plugins]]
# repo = 'justinmk/vim-dirvish' # Minimal Navigator via <-> 
# on_cmd = 'Dirivish'
# on_map = { n = '<Plug>' }

# [[plugins]]
# repo = 'justinmk/vim-dirvish' # Minimal Navigator via <-> 
# on_cmd = 'Dirivish'
# on_map = { n = '<Plug>' }

# [[plugins]]
# repo = 'tpope/vim-eunech' # Unix helpers via <:Delete>, <:Move>, ...
# on_cmd = ['Delete', 'Move']
