# Search - -------------------
# Plugins to search around Vim (via Denite)

[[plugins]]
repo = 'bronson/vim-visual-star-search
on_map = '*'

[[plugins]]
repo = 'Shougo/denite.nvim' # 🐉 Dark powered asynchronous unite all interfaces for Neovim/Vim8
on_cmd = 'Denite'
if = 'has("python3")'
hook_add = '''
" Set Prompt and preferences
call denite#custom#option('default', {
        \ 'cursor_wrap': v:true,
        \ 'auto_resize': v:true,
        \ 'highlight_mode_insert': 'WildMenu'
        \ })

" Change ignore behavior
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
        \ split(&wildignore, ','))

" Change match behavior
call denite#custom#source('file_rec,file_mru', 'matchers',
        \ ['matcher_ignore_globs'])
call denite#custom#source('bookmark,buffer,colorscheme,grep,help,line,outline',
        \ 'matchers', ['matcher_fuzzy'])

" Change sort behavior
call denite#custom#source('file_rec', 'sorters', ['sorter_rank'])

" Navigate Denite via <C-n> and <C-p>
call denite#custom#map(
        \ 'insert',
        \ '<C-n>',
        \ '<denite:move_to_next_line>',
        \ 'noremap'
        \)
        call denite#custom#map(
            \ 'insert',
            \ '<C-p>',
            \ '<denite:move_to_previous_line>',
            \ 'noremap'
            \)

            " Don't exit with <Esc>
            call denite#custom#map('insert', '<Esc>', '<denite:enter_mode:normal>',
                \'noremap')
            call denite#custom#map('normal', '<Esc>', '<NOP>',
                \'noremap')

            " Use Silver Searcher
            if executable('ag')
            call denite#custom#var('file_rec', 'command',
                \ ['ag', '-U', '--hidden', '--follow', '--nocolor', '--nogroup', '-g', ''])

            call denite#custom#var('grep', 'command', ['ag'])
            call denite#custom#var('grep', 'recursive_opts', [])
            call denite#custom#var('grep', 'pattern_opt', [])
        call denite#custom#var('grep', 'separator', ['--'])
        call denite#custom#var('grep', 'final_opts', [])
        call denite#custom#var('grep', 'default_opts',
                \ [ '--skip-vcs-ignores', '--vimgrep', '--smart-case', '--hidden' ])

        " Else Ack
        elseif executable('ack')
        call denite#custom#var('grep', 'command', ['ack'])
        call denite#custom#var('grep', 'recursive_opts', [])
        call denite#custom#var('grep', 'pattern_opt', ['--match'])
        call denite#custom#var('grep', 'separator', ['--'])
        call denite#custom#var('grep', 'final_opts', [])
        call denite#custom#var('grep', 'default_opts',
                \ ['--ackrc', $HOME.'/.config/ackrc', '-H',
                \ '--nopager', '--nocolor', '--nogroup', '--column'])
        endif

        " Keybindings via Leader
        " nnoremap <C-p> :<C-u>Denite file_rec<CR>
        " nnoremap <leader>s :<C-u>Denite buffer<CR>
        " nnoremap <leader><Space>s :<C-u>DeniteBufferDir buffer<CR>
        " nnoremap <leader>8 :<C-u>DeniteCursorWord grep:. -mode=normal<CR>
        " nnoremap <leader>/ :<C-u>Denite grep:. -mode=normal<CR>
        " nnoremap <leader><Space>/ :<C-u>DeniteBufferDir grep:. -mode=normal<CR>
        " nnoremap <leader>d :<C-u>DeniteBufferDir file_rec<CR>
        "
        " hi link deniteMatchedChar Special
        "
        " " denite-extra
        "
        " nnoremap <leader>o :<C-u>Denite location_list -mode=normal -no-empty<CR>
        " nnoremap <leader>hs :<C-u>Denite history:search -mode=normal<CR>
        " nnoremap <leader>hc :<C-u>Denite history:cmd -mode=normal<CR>
        '''
