# Kanagawa Wave for btop

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#dcd7ba"

# Title color for boxes
theme[title]="#c8c093"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7fb4ca"

# Background color of selected item in processes box
theme[selected_bg]="#223249"

# Foreground color of selected item in processes box
theme[selected_fg]="#dcd7ba"

# Color of inactive/disabled text
theme[inactive_fg]="#727169"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#938aa9"

# Box outline colors
theme[cpu_box]="#7e9cd8"
theme[mem_box]="#7e9cd8"
theme[net_box]="#7e9cd8"
theme[proc_box]="#7e9cd8"
theme[div_line]="#54546d"

# Temperature graph colors
theme[temp_start]="#76946a"
theme[temp_mid]="#e6c384"
theme[temp_end]="#e82424"

# CPU graph colors
theme[cpu_start]="#76946a"
theme[cpu_mid]="#e6c384"
theme[cpu_end]="#e82424"

# Memory and disk colors
theme[free_start]="#76946a"
theme[free_mid]="#7aa89f"
theme[free_end]="#7fb4ca"
theme[cached_start]="#7aa89f"
theme[cached_mid]="#7fb4ca"
theme[cached_end]="#957fb8"
theme[available_start]="#76946a"
theme[available_mid]="#7aa89f"
theme[available_end]="#7fb4ca"
theme[used_start]="#e6c384"
theme[used_mid]="#ff9e3b"
theme[used_end]="#e82424"

# Net colors
theme[download_start]="#7aa89f"
theme[download_mid]="#7fb4ca"
theme[download_end]="#7e9cd8"
theme[upload_start]="#957fb8"
theme[upload_mid]="#7e9cd8"
theme[upload_end]="#7fb4ca"
